# Generated by Django 4.0.6 on 2024-03-15 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=10)),
                ('product_id', models.CharField(max_length=10)),
                ('comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='product_models',
            fields=[
                ('product_name', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('token', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('views', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ratings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=10)),
                ('product_id', models.CharField(max_length=10)),
                ('ratings', models.IntegerField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='User_model',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=10)),
                ('registered', models.BooleanField(default=0)),
                ('token', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('comments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='b.comments')),
                ('ratings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='b.ratings')),
            ],
        ),
        migrations.CreateModel(
            name='Business_model',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('contacts', models.IntegerField(max_length=10)),
                ('description', models.TextField()),
                ('token', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('views', models.IntegerField()),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='b.product_models')),
            ],
        ),
    ]
